module conexion_mysql_corva{
    interface corva{
        boolean insertarcorva(in wstring nombre,in wstring apellido, in wstring telefono);
        boolean actualizarcorva(in long id, in wstring nombre,in wstring apellido, in wstring telefono);
        boolean eliminarcorva(in long id);
        wstring consultarcorva(in long id);

        oneway void shoutdown();
        };
     };   