package conexion_mysql_corva;

/**
* conexion_mysql_corva/conexion_mysql_corvaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:14:37 PM COT
*/

public final class conexion_mysql_corvaHolder implements org.omg.CORBA.portable.Streamable
{
  public conexion_mysql_corva.conexion_mysql_corva value = null;

  public conexion_mysql_corvaHolder ()
  {
  }

  public conexion_mysql_corvaHolder (conexion_mysql_corva.conexion_mysql_corva initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = conexion_mysql_corva.conexion_mysql_corvaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    conexion_mysql_corva.conexion_mysql_corvaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return conexion_mysql_corva.conexion_mysql_corvaHelper.type ();
  }

}
