package conexion_mysql_corva;


/**
* conexion_mysql_corva/conexion_mysql_corvaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:14:37 PM COT
*/

public interface conexion_mysql_corvaOperations 
{
  boolean insertarconexion_mysql_corva (String nombre, String apellido, String telefono);
  boolean actualizarconexion_mysql_corva (int id, String nombre, String apellido, String telefono);
  boolean eliminarconexion_mysql_corva (int id);
  String consultarconexion_mysql_corva (int id);
  void shoutdowbn ();
} // interface conexion_mysql_corvaOperations
