package conexion_mysql_corva;


/**
* conexion_mysql_corva/conexion_mysql_corva.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:14:37 PM COT
*/

public interface conexion_mysql_corva extends conexion_mysql_corvaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface conexion_mysql_corva
