package conexion_mysql_corva;


/**
* conexion_mysql_corva/conexion_mysql_corvaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:14:37 PM COT
*/

abstract public class conexion_mysql_corvaHelper
{
  private static String  _id = "IDL:conexion_mysql_corva/conexion_mysql_corva:1.0";

  public static void insert (org.omg.CORBA.Any a, conexion_mysql_corva.conexion_mysql_corva that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static conexion_mysql_corva.conexion_mysql_corva extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (conexion_mysql_corva.conexion_mysql_corvaHelper.id (), "conexion_mysql_corva");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static conexion_mysql_corva.conexion_mysql_corva read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_conexion_mysql_corvaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, conexion_mysql_corva.conexion_mysql_corva value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static conexion_mysql_corva.conexion_mysql_corva narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof conexion_mysql_corva.conexion_mysql_corva)
      return (conexion_mysql_corva.conexion_mysql_corva)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      conexion_mysql_corva._conexion_mysql_corvaStub stub = new conexion_mysql_corva._conexion_mysql_corvaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static conexion_mysql_corva.conexion_mysql_corva unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof conexion_mysql_corva.conexion_mysql_corva)
      return (conexion_mysql_corva.conexion_mysql_corva)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      conexion_mysql_corva._conexion_mysql_corvaStub stub = new conexion_mysql_corva._conexion_mysql_corvaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
