package conexion_mysql_corva;


/**
* conexion_mysql_corva/corva.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:29:28 PM COT
*/

public interface corva extends corvaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface corva
