package conexion_mysql_corva;


/**
* conexion_mysql_corva/corvaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:29:28 PM COT
*/

public interface corvaOperations 
{
  boolean insertarcorva (String nombre, String apellido, String telefono);
  boolean actualizarcorva (int id, String nombre, String apellido, String telefono);
  boolean eliminarcorva (int id);
  String consultarcorva (int id);
  void shoutdown ();
} // interface corvaOperations
