package conexion_mysql_corva;


/**
* conexion_mysql_corva/corvaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:29:28 PM COT
*/

public abstract class corvaPOA extends org.omg.PortableServer.Servant
 implements conexion_mysql_corva.corvaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarcorva", new java.lang.Integer (0));
    _methods.put ("actualizarcorva", new java.lang.Integer (1));
    _methods.put ("eliminarcorva", new java.lang.Integer (2));
    _methods.put ("consultarcorva", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // conexion_mysql_corva/corva/insertarcorva
       {
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarcorva (nombre, apellido, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // conexion_mysql_corva/corva/actualizarcorva
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         String apellido = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarcorva (id, nombre, apellido, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // conexion_mysql_corva/corva/eliminarcorva
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarcorva (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // conexion_mysql_corva/corva/consultarcorva
       {
         int id = in.read_long ();
         String $result = null;
         $result = this.consultarcorva (id);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // conexion_mysql_corva/corva/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:conexion_mysql_corva/corva:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public corva _this() 
  {
    return corvaHelper.narrow(
    super._this_object());
  }

  public corva _this(org.omg.CORBA.ORB orb) 
  {
    return corvaHelper.narrow(
    super._this_object(orb));
  }


} // class corvaPOA
