package conexion_mysql_corva;

/**
* conexion_mysql_corva/corvaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from conexion_mysql_corva.idl
* miércoles 26 de septiembre de 2018 09:29:28 PM COT
*/

public final class corvaHolder implements org.omg.CORBA.portable.Streamable
{
  public conexion_mysql_corva.corva value = null;

  public corvaHolder ()
  {
  }

  public corvaHolder (conexion_mysql_corva.corva initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = conexion_mysql_corva.corvaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    conexion_mysql_corva.corvaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return conexion_mysql_corva.corvaHelper.type ();
  }

}
